javac Application.java Calculation.java ExCalculation.java
javac Application.java Calculation.java ExCalculation.java
javac Application.java Calculation.java ExCalculation.java
javac Application.java Calculation.java ExCalculation.java
java -Xmx128M -Xms16M Application
javac Application.java Calculation.java ExCalculation.java
javac Application.java Calculation.java ExCalculation.java
java -Xmx128M -Xms16M Application
javac Application.java Calculation.java ExCalculation.java
java -Xmx128M -Xms16M Application
javac Application.java Calculation.java ExCalculation.java
java -Xmx128M -Xms16M Application
javac Application.java Calculation.java ExCalculation.java
javac Application.java Calculation.java ExCalculation.java
java -Xmx128M -Xms16M Application
javac Application.java Calculation.java ExCalculation.java
javac Application.java Calculation.java ExCalculation.java
javac Application.java Calculation.java ExCalculation.java
javac Application.java Calculation.java ExCalculation.java
